services:
    acme_store.admin.category:
        class: Acme\StoreBundle\Admin\CategoryAdmin
        arguments: [~, Acme\StoreBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Category, label: Category}
            
    acme.store.menu.voter.request:
        class: Acme\StoreBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }           
