Acme\RecipeBundle\Entity\Ingredient:
    type: entity
    table: ingredient
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        dimension:
            type: string
            nullable: false
            length: 20
            fixed: false
    lifecycleCallbacks: {  }
