Acme\RecipeBundle\Entity\Recipes:
    type: entity
    table: recipes
    indexes:
        user:
            columns:
                - user_id
        composite:
            columns:
                - composite_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
    manyToOne:
        composite:
            targetEntity: Composite
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                composite_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Acme\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
